export const INCIDENT_CHANGE_TAB = "INCIDENT_CHANGE_TAB";
export type INCIDENT_CHANGE_TAB = typeof INCIDENT_CHANGE_TAB;

export const INCIDENT_TOGGLE_CAM = "INCIDENT_TOGGLE_CAM";
export type INCIDENT_TOGGLE_CAM = typeof INCIDENT_TOGGLE_CAM;

export const INCIDENT_SETUP_DATA = "INCIDENT_SETUP_DATA";
export type INCIDENT_SETUP_DATA = typeof INCIDENT_SETUP_DATA;

export const INCIDENT_SAVE_DATA = "INCIDENT_SAVE_DATA";
export type INCIDENT_SAVE_DATA = typeof INCIDENT_SAVE_DATA;

export const INCIDENT_GET_DETAIL = "INCIDENT_GET_DETAIL";
export type INCIDENT_GET_DETAIL = typeof INCIDENT_GET_DETAIL;

export const INCIDENT_SET_DETAIL = "INCIDENT_SET_DETAIL";
export type INCIDENT_SET_DETAIL = typeof INCIDENT_SET_DETAIL;

export const INCIDENT_UPDATE_DATA = "INCIDENT_UPDATE_DATA";
export type INCIDENT_UPDATE_DATA = typeof INCIDENT_UPDATE_DATA;

export const INCIDENT_SAVE_CLIP = "INCIDENT_SAVE_CLIP";
export type INCIDENT_SAVE_CLIP = typeof INCIDENT_SAVE_CLIP;

export const INCIDENT_PLAY_CLIP = "INCIDENT_PLAY_CLIP";
export type INCIDENT_PLAY_CLIP = typeof INCIDENT_PLAY_CLIP;

export const INCIDENT_RELEASE_PLAYING_CLIP = "INCIDENT_RELEASE_PLAYING_CLIP";
export type INCIDENT_RELEASE_PLAYING_CLIP = typeof INCIDENT_RELEASE_PLAYING_CLIP;

export const INCIDENT_SAVE_NOTE = "INCIDENT_SAVE_NOTE";
export type INCIDENT_SAVE_NOTE = typeof INCIDENT_SAVE_NOTE;

export const INCIDENT_EDIT_NOTE = "INCIDENT_EDIT_NOTE";
export type INCIDENT_EDIT_NOTE = typeof INCIDENT_EDIT_NOTE;

export const INCIDENT_DELETE_NOTE = "INCIDENT_DELETE_NOTE";
export type INCIDENT_DELETE_NOTE = typeof INCIDENT_DELETE_NOTE;

export * from "./Map";
