export const LOAD_VIDEO_WALLS = "LOAD_VIDEO_WALLS";
export type LOAD_VIDEO_WALLS = typeof LOAD_VIDEO_WALLS;

export const SET_LIST_CCTVS = "SET_LIST_CCTVS";
export type SET_LIST_CCTVS = typeof SET_LIST_CCTVS;

export const LOAD_CCTVS = "LOAD_CCTVS";
export type LOAD_CCTVS = typeof LOAD_CCTVS;

export const SET_LIST_VIDEO_WALLS = "SET_LIST_VIDEO_WALLS";
export type SET_LIST_VIDEO_WALLS = typeof SET_LIST_VIDEO_WALLS;

export const SET_VIDEO_WALL = "SET_VIDEO_WALL";
export type SET_VIDEO_WALL = typeof SET_VIDEO_WALL;

export const CREATE_VIDEO_WALL = "CREATE_VIDEO_WALL";
export type CREATE_VIDEO_WALL = typeof CREATE_VIDEO_WALL;

export const UPDATE_VIDEO_WALL = "UPDATE_VIDEO_WALL";
export type UPDATE_VIDEO_WALL = typeof UPDATE_VIDEO_WALL;

export const DELETE_VIDEO_WALL = "DELETE_VIDEO_WALL";
export type DELETE_VIDEO_WALL = typeof DELETE_VIDEO_WALL;

export const SET_TOOLBAR_STATUS = "SET_TOOLBAR_STATUS";
export type SET_TOOLBAR_STATUS = typeof SET_TOOLBAR_STATUS;

export const LOAD_CAMERA_LAYOUT = "LOAD_CAMERA_LAYOUT";
export type LOAD_CAMERA_LAYOUT = typeof LOAD_CAMERA_LAYOUT;

export const SELECT_CAMERA_LAYOUT = "SELECT_CAMERA_LAYOUT";
export type SELECT_CAMERA_LAYOUT = typeof SELECT_CAMERA_LAYOUT;

export const SELECT_WALL_TILE = "SELECT_WALL_TILE";
export type SELECT_WALL_TILE = typeof SELECT_WALL_TILE;

export const UN_SELECT_WALL_TILE = "UN_SELECT_WALL_TILE";
export type UN_SELECT_WALL_TILE = typeof UN_SELECT_WALL_TILE;

export const UPDATE_WALL_TILE = "UPDATE_WALL_TILE";
export type UPDATE_WALL_TILE = typeof UPDATE_WALL_TILE;

export const SET_FULL_SCREEN = "SET_FULL_SCREEN";
export type SET_FULL_SCREEN = typeof SET_FULL_SCREEN;

export const SHOW_CAMERA_LAYOUT = "SHOW_CAMERA_LAYOUT";
export type SHOW_CAMERA_LAYOUT = typeof SHOW_CAMERA_LAYOUT;

export const LOAD_LIST_CAMERA = "LOAD_LIST_CAMERA";
export type LOAD_LIST_CAMERA = typeof LOAD_LIST_CAMERA;

export const SET_LIST_CAMERA = "SET_LIST_CAMERA";
export type SET_LIST_CAMERA = typeof SET_LIST_CAMERA;

export const ADD_TILE = "ADD_TILE";
export type ADD_TILE = typeof ADD_TILE;

export const REMOVE_TILE = "REMOVE_TILE";
export type REMOVE_TILE = typeof REMOVE_TILE;

export const UPDATE_CUSTOM_TILE = "UPDATE_CUSTOM_TILE";
export type UPDATE_CUSTOM_TILE = typeof UPDATE_CUSTOM_TILE;

export const UPDATE_CUSTOM_LAYOUT = "UPDATE_CUSTOM_LAYOUT";
export type UPDATE_CUSTOM_LAYOUT = typeof UPDATE_CUSTOM_LAYOUT;

export const INIT_VIDEO_WALL = "INIT_VIDEO_WALL";
export type INIT_VIDEO_WALL = typeof INIT_VIDEO_WALL;
