export const LOGS_MGNT_SET_PAGE = "LOGS_MGNT_SET_PAGE";
export type LOGS_MGNT_SET_PAGE = typeof LOGS_MGNT_SET_PAGE;

export const LOGS_MGNT_SEARCH = "LOGS_MGNT_SEARCH";
export type LOGS_MGNT_SEARCH = typeof LOGS_MGNT_SEARCH;

export const LOGS_MGNT_UPDATE_FILTER = "LOGS_MGNT_UPDATE_FILTER";
export type LOGS_MGNT_UPDATE_FILTER = typeof LOGS_MGNT_UPDATE_FILTER;
