export const CLOSE_FLOATING_VIDEO = "CLOSE_FLOATING_VIDEO";
export type CLOSE_FLOATING_VIDEO = typeof CLOSE_FLOATING_VIDEO;

export const OPEN_FLOATING_VIDEO = "OPEN_FLOATING_VIDEO";
export type OPEN_FLOATING_VIDEO = typeof OPEN_FLOATING_VIDEO;

export const VIDEO_CONTROL = "VIDEO_CONTROL";
export type VIDEO_CONTROL = typeof VIDEO_CONTROL;
