export const MANAGEMENT_CCTV_GET_LIST_CCTV = "MANAGEMENT_CCTV_GET_LIST_CCTV";
export type MANAGEMENT_CCTV_GET_LIST_CCTV = typeof MANAGEMENT_CCTV_GET_LIST_CCTV;

export const MANAGEMENT_CCTV_SET_LIST_CCTV = "MANAGEMENT_CCTV_SET_LIST_CCTV";
export type MANAGEMENT_CCTV_SET_LIST_CCTV = typeof MANAGEMENT_CCTV_SET_LIST_CCTV;

export const MANAGEMENT_CCTV_SET_LIST_CCTV_STATE =
  "MANAGEMENT_CCTV_SET_LIST_CCTV_STATE";
export type MANAGEMENT_CCTV_SET_LIST_CCTV_STATE = typeof MANAGEMENT_CCTV_SET_LIST_CCTV_STATE;

export const MANAGEMENT_CCTV_CREATE_CCTV = "MANAGEMENT_CCTV_CREATE_CCTV";
export type MANAGEMENT_CCTV_CREATE_CCTV = typeof MANAGEMENT_CCTV_CREATE_CCTV;

export const MANAGEMENT_CCTV_EDIT_CCTV = "MANAGEMENT_CCTV_EDIT_CCTV";
export type MANAGEMENT_CCTV_EDIT_CCTV = typeof MANAGEMENT_CCTV_EDIT_CCTV;

export const MANAGEMENT_CCTV_GET_CCTV = "MANAGEMENT_CCTV_GET_CCTV";
export type MANAGEMENT_CCTV_GET_CCTV = typeof MANAGEMENT_CCTV_GET_CCTV;

export const MANAGEMENT_CCTV_SET_CCTV = "MANAGEMENT_CCTV_SET_CCTV";
export type MANAGEMENT_CCTV_SET_CCTV = typeof MANAGEMENT_CCTV_SET_CCTV;
