export const SHOW_ADD_VIDEO_WALL_DIALOG = "SHOW_ADD_VIDEO_WALL_DIALOG";
export type SHOW_ADD_VIDEO_WALL_DIALOG = typeof SHOW_ADD_VIDEO_WALL_DIALOG;

export const ADD_CAMERA_TO_VIDEO_WALL = "ADD_CAMERA_TO_VIDEO_WALL";
export type ADD_CAMERA_TO_VIDEO_WALL = typeof ADD_CAMERA_TO_VIDEO_WALL;

export const SET_CAMERA_ID = "ADD_VIDEO_WALL/SET_CAMERA_ID";
export type SET_CAMERA_ID = typeof SET_CAMERA_ID;

export const SET_LIST_CAMERA_ID = "ADD_VIDEO_WALL/SET_LIST_CAMERA_ID";
export type SET_LIST_CAMERA_ID = typeof SET_LIST_CAMERA_ID;
