export const OPEN_CAMERA_VIEW = "OPEN_CAMERA_VIEW";
export type OPEN_CAMERA_VIEW = typeof OPEN_CAMERA_VIEW;

export const CLOSE_CAMERA_VIEW = "CLOSE_CAMERA_VIEW";
export type CLOSE_CAMERA_VIEW = typeof CLOSE_CAMERA_VIEW;

export const LOAD_CAMERA_VIEW = "LOAD_CAMERA_VIEW";
export type LOAD_CAMERA_VIEW = typeof LOAD_CAMERA_VIEW;

export const LOAD_RECORD_VIDEO = "LOAD_RECORD_VIDEO";
export type LOAD_RECORD_VIDEO = typeof LOAD_RECORD_VIDEO;

export const LOAD_RECORD_VIDEO_LOGS = "LOAD_RECORD_VIDEO_LOGS";
export type LOAD_RECORD_VIDEO_LOGS = typeof LOAD_RECORD_VIDEO_LOGS;

export const SET_RECORD_VIDEO = "SET_RECORD_VIDEO";
export type SET_RECORD_VIDEO = typeof SET_RECORD_VIDEO;

export const SET_RECORD_VIDEO_LOGS = "SET_RECORD_VIDEO_LOGS";
export type SET_RECORD_VIDEO_LOGS = typeof SET_RECORD_VIDEO_LOGS;

export const SAVE_RECORD_VIDEO = "SAVE_RECORD_VIDEO";
export type SAVE_RECORD_VIDEO = typeof SAVE_RECORD_VIDEO;

export const UPDATE_TAB_CAMERA_VIEW = "UPDATE_TAB_CAMERA_VIEW";
export type UPDATE_TAB_CAMERA_VIEW = typeof UPDATE_TAB_CAMERA_VIEW;
