export const GET_CAM_POINTS = "GET_CAM_POINTS";
export type GET_CAM_POINTS = typeof GET_CAM_POINTS;

export const SET_CAM_POINTS = "SET_CAM_POINTS";
export type SET_CAM_POINTS = typeof SET_CAM_POINTS;

export const UPDATE_CAM_POINTS = "UPDATE_CAM_POINTS";
export type UPDATE_CAM_POINTS = typeof UPDATE_CAM_POINTS;

export const SET_SEARCH_RESULT_CAM_POINTS = "SET_SEARCH_RESULT_CAM_POINTS";
export type SET_SEARCH_RESULT_CAM_POINTS = typeof SET_SEARCH_RESULT_CAM_POINTS;

export const SET_SEARCH_MODE_MAIN_MAP = "SET_SEARCH_MODE_MAIN_MAP";
export type SET_SEARCH_MODE_MAIN_MAP = typeof SET_SEARCH_MODE_MAIN_MAP;
