export const SET_SEARCH_RESULT_INCIDENTS = "SET_SEARCH_RESULT_INCIDENTS";
export type SET_SEARCH_RESULT_INCIDENTS = typeof SET_SEARCH_RESULT_INCIDENTS;

export const SET_SEARCH_CONFIG_INCIDENTS = "SET_SEARCH_CONFIG_INCIDENTS";
export type SET_SEARCH_CONFIG_INCIDENTS = typeof SET_SEARCH_CONFIG_INCIDENTS;

export const SET_SEARCH_STATE_INCIDENTS = "SET_SEARCH_STATE_INCIDENTS";
export type SET_SEARCH_STATE_INCIDENTS = typeof SET_SEARCH_STATE_INCIDENTS;

export const GET_SEARCH_RESULT_INCIDENTS = "GET_SEARCH_RESULT_INCIDENTS";
export type GET_SEARCH_RESULT_INCIDENTS = typeof GET_SEARCH_RESULT_INCIDENTS;
